### ISSUE TITLE
How is the project different to Actix?

### ISSUE THREAD

**Issue by atroche** [rsimmonsjr/axiom#103]
This question that stood out in my mind after reading the readme. I use Actix at the moment. Is there any reason to consider switching?
Cheers!

**Comment by khionu** [comment]
Actix is a pseudo actor model. It provides a vaguely similar feel which can _promote_ the safeties an actor model can provide, but it is not actually an actor model.

As with any dependency change, default to not switching unless you find there is good reason to do. If you're invested in Actix and have a stable service, it could very well not be worth the effort.

Additionally, this does not have any of the web services that Actix's design was made to support. This is a raw actor model, and you'd need to incorporate another web server in conjunction with Axiom.

**Comment by khionu** [comment]
I'm going to close this issue. If you have any further questions of a general nature, I would encourage you to reach out to me on Discord (Khionu#0047).

**Comment by atroche** [comment]
Thanks, I appreciate the response and the advice!
