### ISSUE TITLE
[Ergonomics] Add ease-of-use return utility

### ISSUE THREAD

**Issue by khionu** [rsimmonsjr/axiom#110]
With the Async Refactor, we are having users return the state to us. This creates return expression complication, as `Ok(Status::Done)` is now `Ok((state, Status::Done))`. This is needlessly verbose. Options to be considered:
- Declarative macro
- Procedural macro
- From implementations

**Comment by rsimmonsjr** [comment]
I would propose a syntax like ```rust
Status::done(state);
```
This would allow us to make the system easier to use without reaching immediately for macros.

**Comment by khionu** [comment]
Sure, that's reasonable. Should that automatically wrap it in `Ok()` as well, or would that be a little too much erasure?

**Comment by khionu** [comment]
Added in 1fd90b6fb583d269908b973ae642c7644541ed5c
