### ISSUE TITLE
Will this project introduce async-std as the dependency?

### ISSUE THREAD

**Issue by apehub** [rsimmonsjr/axiom#115]
Hi @rsimmonsjr ,
I am studying rust actor libraries these days, I have studied "actix" and "axiom", and from my point of view, I like axiom much more than actix, since it looks much more clear and easier.

In the rust v1.39 release, the async/await features are now included in rust, and the "async-std" crate has fully implemented those feature. Is there any plan to use "async-std" as the synchronize/concurrency library in axiom project?

**Comment by khionu** [comment]
There's nothing stopping the *user* from using `async-std`, but you can't use it as an Executor. Any of its async functions and Futures will run in Axiom's Executor if called from in an Actor.

Axiom will not be importing Tokio or `async-std`, itself, as there is no need, and it would add considerable weight to the dependencies.

Note, our next steps include providing TCP and UDP functionality in a message-driven API, which optimize async networking for our implementation of the Actor Model.

**Comment by khionu** [comment]
Closing this issue as resolved. If this was not answered sufficiently, feel free to reopen. If you have further questions, you can open another issue, or ask on our [Discord](https://discord.gg/8MHVCzr).
