### ISSUE TITLE
Consider fixed Reactor count for defaults rather than num_cpus

### ISSUE THREAD

**Issue by khionu** [rsimmonsjr/axiom#133]
It's a whole dependency that we don't need. We can guess that servers will likely have at least 8 cores, and a default of 32 reactors for a server with 4 cores is likely to not be overkill. If this is being used on a desktop, then other optimizations would need to be made anyways.

**Comment by khionu** [comment]
@rsimmonsjr If you have no objections, I'd like to do this.

**Comment by rsimmonsjr** [comment]
That's fine, this is a default setup for the system and not problematic to change. I am testing 2.1 stuff now with my stuff.
