### ISSUE TITLE
Create a Means to allow the ActorSystem to finish all messages before shutting down.

### ISSUE THREAD

**Issue by rsimmonsjr** [rsimmonsjr/axiom#45]
Currently Shutdown is a bit brutal, messages are stranded in the channels. This ticket is to add an additional shutdown process that makes sure all messages are processed and sends stop to all actors so that they can wrap up work before the threads exit.

**Comment by icefoxen** [comment]
Would this include stopping new messages being sent to actors? I'm a little worried about an actor never shutting down because something keeps sending it new messages.

**Comment by rsimmonsjr** [comment]
> Would this include stopping new messages being sent to actors? I'm a little worried about an actor never shutting down because something keeps sending it new messages.

That would definitely be a danger. The reason I conceived of the feature is to allow actor systems to shut down gracefully in situations where they act as a server. Even if I put the option in, it would be only an option. The existing API and behavior would not be broken.

**Comment by icefoxen** [comment]
That sounds reasonable. I'm just working on a thing with real-time requirements, so lots of control over shutdown is desirable. It just occurred to me I can implement that as  a generic additional layer of logic in my actors though.

**Comment by rsimmonsjr** [comment]
Awesome. I also accept PRs if you have feature ideas.

**Comment by rsimmonsjr** [comment]
This is actually not feasible because of message flow in the system. The user should take alternative approaches such as bleeding off connections or making the actors close down individually with custom messages. Therefore I am closing this issue.
