### ISSUE TITLE
Design question: pattern match on message type?

### ISSUE THREAD

**Issue by icefoxen** [rsimmonsjr/axiom#53]
I'm used to Erlang's pattern of feeding an actor message into a pattern match, and the chains of `if let Some(x) = msg.content_as::<Foo>()` feels clunky in comparison. I know there's only so much one can do with `TypeId` but I was wondering if you had any thoughts on whether it would be possible to have a nicer pattern?

Another concern I have that I don't know the answer to is whether `TypeId` is stable between compiler version, or even multiple builds of the same program. If not, having multiple separate programs in the same cluster could lead to their `TypeId`'s being incompatible...

**Comment by rsimmonsjr** [comment]
TypeId should not be depended on when compiled on different machines and that is not recommended. When running an Axiom Cluster (after I get that finished) the recommendation will be to deploy the same compiled binary on all nodes. 

As for the pattern match, Rust doesn't have the ability to type match in pattern match on Any instances at the current time so downcast is the only possibility. The downcast is, however, very fast and should not be worried about. Keep in mind Erlang pattern match is still just syntactic sugar over an if else block anyway and someone could write a macro for Axiom if they chose to make it more "sugary". :) I dont have the bandwidth for that now as I am trying to implement remote actors.

**Comment by icefoxen** [comment]
Yeah, after some thought and research I can't come up with a better solution to this either.  Since it's just an ergonomic matter, not actually functional, I can only care so much.
