### ISSUE TITLE
Semantics and limits of TypeId

### ISSUE THREAD

**Issue by icefoxen** [rsimmonsjr/axiom#57]
From #53: 

> TypeId should not be depended on when compiled on different machines and that is not recommended. When running an Axiom Cluster (after I get that finished) the recommendation will be to deploy the same compiled binary on all nodes.

I want to throw down some thoughts I have about `TypeId` and see what you think of them, so that I can get them straight in my own head, and hopefully someone will find this useful someday down the line.

First, I'm coming from ROS, which is designed to allow multiple programs to operate together, even written in different languages, and basically implements a message-based RPC system complete with message definition files similar to gRPC or Cap'n Proto.  I sure as heck don't want to build something as complicated as that, but there are certain advantages that come out of it that I do kinda do want:

 * You can have external programs that record/replay/produce messages for simulation and testing
 * You can start up a new node that connects to a running system and acts as a debugger to inspect what's going on in some detail

Your recommendation for using the same binary for every node in a cluster makes sense for something scaling horizontally like a web service, but is less convenient for something with lots of asymmetric parts like a robot system.  If rebuilding your debugger program requires rebuilding and re-deploying your whole system, and that system is fundamentally stateful, that gets annoying and slow.

So I guess my question is, what *can* we reliably do with `TypeId`, and what are the exact constraints?  How far can we rely on ` TypeId::of::<u32>() == whatever` being accurate?  Obviously if everything is built into one statically-linked binary, all `TypeId`'s will line up with each other.  And the [`TypeId` docs](https://doc.rust-lang.org/std/any/struct.TypeId.html) say "...it is worth noting that the hashes and ordering will vary between Rust releases. Beware of relying on them inside of your code!", so that's the other extreme. But "same compiler" is pretty easy to guarantee, and the docs don't say a whole lot beyond that.  So, will `TypeId` comparisons be valid if:

 * ...we build multiple binaries as part of the same crate?
 * ...we build multiple dylib's as part of the same crate?
 * ...we build multiple totally independent binaries using the same types (say, a common crate full of type definitions)?
 * ...we build multiple totally independent binaries using the same types, but for different targets?  x86_64 vs aarch64, for example.

**Comment by icefoxen** [comment]
Okay, some research:

 * `TypeId` is a `u64` and implemented with compiler intrinsics: https://doc.rust-lang.org/std/intrinsics/fn.type_id.html
 * That function claims "This function will return the same value for a type regardless of whichever crate it is invoked in.", but is unstable/nightly so that promise may change.
 * The actual implementation of that function is part of `librustc_codegen_llvm/intrinsic.rs`
 * That hashes the type using this code: https://github.com/rust-lang/rust/blob/master/src/librustc/ty/util.rs#L226-L245 which produces a hash of the actual type definition, not just an arbitrary index assigned to each unique type in a crate.  The actual hasher used is a SipHash using this code: https://github.com/rust-lang/rust/blob/master/src/librustc_data_structures/stable_hasher.rs which is particularly intended to hash types in a predictable fashion -- it handles endianness, `usize` variations and so on.  It is also used to generate hashes for symbol ID's and such for the code rustc emits

Conclusions:

 * It's an unstable API but a pretty good one that provides guarantees that rustc needs, so it will probably not change often.
 * The comments note that it is intended to be independent of source architecture -- if you are compiling for x86_64 you will get the same hashes out of a given type regardless of what platform you are building *on*.  The inverse is not necessarily true -- a `TypeId` for the same program built *for* x86_64 vs aarch64 is not guaranteed to be the same --  it looks like it probably will be in practice, but you can't promise it.
 * I don't see any provisions for hash collisions or such in the `type_of::<T>()` code, so they *are* possible.  Also, SipHash is not designed to be crypto secure, so given a hash it is probably possible to deliberately craft an input that collides with it.  On the other hand, in the docs for [the `HashStable` trait](https://github.com/rust-lang/rust/blob/master/src/librustc_data_structures/stable_hasher.rs) specifically says "`x != y` implies `hash_stable(x) != hash_stable(y)`", which makes collisions impossible, though I don't see yet how it does this.  It also says "`hash_stable()` must be independent of the current compilation session. E.g. they must not hash memory addresses or other things that are "randomly" assigned per compilation session."

**Comment by icefoxen** [comment]
So, the only ACTUAL promise that Rust makes about `TypeId` is what the docs say: It is "globally unique" (which is not very helpful without further definition), and it is not comparable between different Rust releases.  But what the actual IMPLEMENTATION promises (as of rustc 1.37) is that by "globally unique" they pretty much mean what it says on the tin: with the exception of programs built for different targets, two `TypeId`'s for the same type will be comparable regardless of what program they are part of, they will never collide, and rustc relies on this behavior for things other than `TypeId` so it probably won't change quickly.

So if you are willing to rely on implementation-defined behavior a little, the answers are:

 * Can we build multiple binaries as part of the same crate?  YES
 * Can we build multiple dylib's as part of the same crate?  YES
 * Can we build multiple totally independent binaries using the same types (say, a common crate full of type definitions)?  YES
 * Can we build multiple totally independent binaries using the same types, but for different targets? x86_64 vs aarch64, for example.  PROBABLY, but don't do it.

It may not be too hard to get the lang team to commit to a stricter definition of `TypeId` matching the current implementation, or at least clarify how global they actually mean by "global".

**Comment by icefoxen** [comment]
A follow up on `HashStable` making collisions impossible, "though I don't see yet how it does this"...  It doesn't.  Though it's a known bug:  https://github.com/rust-lang/rust/issues/10389

**Comment by rsimmonsjr** [comment]
I am sort of unclear on your general recommendation and point. Can you clarify?

**Comment by icefoxen** [comment]
The point is basically me trying to figure out what one can and can't do with `TypeId`, since the official documentation is pretty brief about its constraints.

The state of affairs is "in principle we can do a lot with it, but its current implementation may break silently on a hash collision, and this is a known rustc bug".  It's a 64-bit number with a good hash function behind it, so an accidental collision isn't something I'm going to worry about in day to day life, but it would be nice if it were fixed someday.

**Comment by rsimmonsjr** [comment]
I think that is a risk that is unavoidable at this point. Without RTTI it is otherwise impossible to deserialize the message in the channel and keep it type agnostic. Is there another suggestion?

**Comment by icefoxen** [comment]
I mean, the point is that `TypeId` more or less *is* your RTTI and it's a little broken.  Apart from figuring that out, no, no other suggestions.

**Comment by rsimmonsjr** [comment]
Well its definitely something we should keep an eye on.

**Comment by rsimmonsjr** [comment]
Didn't mean to close. Will leave user to do that if he is satisfied.
