### ISSUE TITLE
Add graceful shutdown for threads handling remotes. 

### ISSUE THREAD

**Issue by rsimmonsjr** [rsimmonsjr/axiom#76]
Currently the threads are just flat terminated. It would be better if they are gracefully shutdown and they inform the remotes that they are shut down. This could be wrapped up in a protocol for system to system communication.

**Comment by rsimmonsjr** [comment]
The simplest way to do this is alter all the mechanisms that spawn threads and have them add the thread to the vec of join handles and then only when they are all done would they notify. Creation of  `thread_started` and `thread_joined` functions to handle this, without exposing that API to the public would be optimal.

**Comment by khionu** [comment]
We can actually move these threads into their own Reactors and have them owned by the Executor. At the same time, I can refactor thread shutdown into AxiomThreadPool. Ideally, all threads used by the ActorSystem should go through AxiomThreadPool, so they can make use of the same shutdown features.

**Comment by khionu** [comment]
Closing this in favour of #114.
