### ISSUE TITLE
Rename Statuses. 

### ISSUE THREAD

**Issue by rsimmonsjr** [rsimmonsjr/axiom#78]
To make Status more consistent the variants should have constant cognitive theme.
`Processed` should be renamed `Consume`
`Skipped` should be renamed: `Skip`

Note that it might entail renaming status as well because its really a verb. Maybe `Action`

**Comment by icefoxen** [comment]
`Action` seems reasonable, since it's the action the actor took with the message. I do like the past tense though, I didn't notice that it was inconsistent.

**Comment by rsimmonsjr** [comment]
After consideration will use: 

`Status {Done, Skip, Reset, Stop}`

**Comment by rsimmonsjr** [comment]
Done
